# Generated by Django 5.2 on 2026-03-15 00:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0002_alter_transactions_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactions',
            old_name='transaction_type',
            new_name='type',
        ),
        migrations.AddField(
            model_name='transactions',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactions',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
