# Generated by Django 5.2 on 2026-03-15 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0003_rename_transaction_type_transactions_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactions',
            old_name='user_id',
            new_name='user',
        ),
    ]
