# Generated by Django 5.2 on 2026-03-15 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0004_rename_user_id_transactions_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transactions',
            new_name='Transaction',
        ),
    ]
