# Generated by Django 5.2 on 2026-03-21 02:37

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0008_alter_category_options_alter_transaction_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Transaction', 'verbose_name_plural': 'Transactions'},
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['category'], name='Finance_tra_categor_48bee6_idx'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('value__gte', Decimal('0.01000000000000000020816681711721685132943093776702880859375'))), name='value_min_range'),
        ),
    ]
