# Generated by Django 5.2 on 2026-03-28 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0010_category_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='transaction_type',
            field=models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], max_length=10),
        ),
    ]
