# Generated by Django 5.2 on 2026-03-28 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0011_alter_category_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(blank=True, choices=[('income', 'Income'), ('expense', 'Expense')], max_length=10, null=True),
        ),
    ]
