# Generated by Django 5.2 on 2026-04-02 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0012_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
