# Generated by Django 5.2 on 2026-04-02 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0014_user_email_verification_token_user_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email_verification_token',
        ),
    ]
