# Generated by Django 5.2.12 on 2026-04-12 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0017_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
