# Generated by Django 5.2.12 on 2026-04-21 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0018_transaction_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-created_at'], 'verbose_name': 'Transaction', 'verbose_name_plural': 'Transactions'},
        ),
    ]
