# Generated by Django 5.2.12 on 2026-04-25 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0019_alter_transaction_options'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'created_at'], name='Finance_tra_user_id_5bca48_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'transaction_type'], name='Finance_tra_user_id_e72bd1_idx'),
        ),
    ]
